import { Chain } from '../types';

module.exports = {
  name: 'The lore',
  description: 'The serie who give lore to the text',
  emoji: '📖',
  languages: [
    'Haitian Creole',
    'Japanese',
    'Chinese (Traditional)',
    'Maori',
    'Igbo',
    'Javanese',
    'Scots Gaelic',
    'Tagalog (Filipino)',
    'Vietnamese',
    'German',
    'French',
    'Hindi',
    'Esperanto',
    'Lao',
    'Russian',
    'Nepali',
    'Latin',
    'Frisian',
    'Spanish',
    'Tatar',
    'Greek',
    'Korean',
    'Igbo',
    'English',
    'Russian',
    'Arabic',
    'Zulu',
    'Kinyarwanda',
    'Galician',
    'Japanese',
    'Hausa',
    'Sesotho',
    'Kannada',
    'Chinese (Simplified)',
    'Hausa',
    'Sindhi',
    'Samoan',
    'Cebuano',
    'Albanian',
    'Indonesian',
    'Luxembourgish',
    'Czech',
    'Lao',
    'Chinese (Traditional)',
    'Kannada',
    'Korean',
    'Latin',
    'Dutch',
    'Japanese',
    'Tagalog (Filipino)',
    'Finnish',
  ],
} as Chain;
