import { Serie } from '../types';

module.exports = {
  name: 'The LORE',
  description:
    "Everything of this serie have lore, so if you search lore, it's here",
  emoji: '📕',
  languages: () => [
    'Haitian Creole',
    'Japanese',
    'Chinese (Traditional)',
    'Maori',
    'Igbo',
    'Javanese',
    'Scots Gaelic',
    'Filipino',
    'Vietnamese',
    'German',
    'French',
    'Hindi',
    'Esperanto',
    'Lao',
    'Russian',
    'Nepali',
    'Latin',
    'Frisian',
    'Spanish',
    'Turkish',
    'Greek',
    'Korean',
    'Igbo',
    'English',
    'Russian',
    'Arabic',
    'Zulu',
    'Swahili',
    'Galician',
    'Japanese',
    'Hausa',
    'Sesotho',
    'Kannada',
    'Chinese (Simplified)',
    'Hausa',
    'Sindhi',
    'Samoan',
    'Cebuano',
    'Albanian',
    'Indonesian',
    'Luxembourgish',
    'Czech',
    'Lao',
    'Chinese (Traditional)',
    'Kannada',
    'Korean',
    'Latin',
    'Dutch',
    'Japanese',
    'Filipino',
    'Finnish',
  ],
} as Serie;
