import { Serie } from '../types';

module.exports = {
  name: 'The Lunatic',
  description: '1... 2... 3... 123Languages for this serie',
  emoji: '🌙',
  languages: () => [
    'Javanese',
    'Greek',
    'Chinese (Simplified)',
    'Japanese',
    'French',
    'Myanmar (Burmese)',
    'Haitian Creole',
    'Afrikaans',
    'Indonesian',
    'Igbo',
    'Arabic',
    'English',
    'Dutch',
    'Kyrgyz',
    'Swahili',
    'Esperanto',
    'Zulu',
    'English',
    'Chichewa',
    'Malay',
    'Spanish',
    'Lao',
    'Welsh',
    'Japanese',
    'Sundanese',
    'Kurdish (Kurmanji)',
    'Nepali',
    'Tajik',
    'Haitian Creole',
    'Pashto',
    'Uzbek',
    'Turkish',
    'Esperanto',
    'Basque',
    'Chinese (Traditional)',
    'Khmer',
    'French',
    'Frisian',
    'Punjabi',
    'Icelandic',
    'Urdu',
    'Russian',
    'Javanese',
    'Malagasy',
    'Maori',
    'Vietnamese',
    'Spanish',
    'Japanese',
    'Korean',
    'English',
    'Basque',
    'Samoan',
    'Cebuano',
    'Albanian',
    'Indonesian',
    'Luxembourgish',
    'Czech',
    'French',
    'English',
    'Japanese',
    'Korean',
    'Bengali',
    'Mongolian',
    'Somali',
    'Thai',
    'Zulu',
    'Lithuanian',
    'Hmong',
    'Chinese (Simplified)',
    'Arabic',
    'Korean',
    'Malayalam',
    'Spanish',
    'Russian',
    'Japanese',
    'French',
    'English',
    'Latin',
    'Greek',
    'Italian',
    'Latvian',
    'Somali',
    'Russian',
    'Chichewa',
    'Corsican',
    'Indonesian',
    'Icelandic',
    'Chinese (Traditional)',
    'German',
    'Japanese',
    'Catalan',
    'Luxembourgish',
    'Arabic',
    'Myanmar (Burmese)',
    'Russian',
    'Zulu',
    'Haitian Creole',
    'Serbian',
    'Xhosa',
    'Catalan',
    'Portuguese',
    'Chichewa',
    'Kyrgyz',
    'Hindi',
    'Croatian',
    'Bengali',
    'Luxembourgish',
    'Telugu',
    'Xhosa',
    'Javanese',
    'Greek',
    'Chinese (Simplified)',
    'Japanese',
    'French',
    'Korean',
    'Arabic',
    'Khmer',
    'Macedonian',
    'Uzbek',
    'Dutch',
    'Chinese (Traditional)',
    'Finnish',
  ],
} as Serie;
